### ISSUE TITLE
Doesn't lint `@import` scss in Vue SFC <style> block

### ISSUE THREAD

**Issue by ModyQyW** [ModyQyW/vite-plugin-stylelint#9]
Importing a test.scss in that scope doesn't lint that test.scss still (it does compile!)

index.vue:
```
<style lang="scss" scoped>
@import "test";
</style>
```
test.scss:
```
.glorp {
  margin: 0;
  font-size: 40px;
      padding: 12px;
        clor: yellow;
}

```

test.scss DOES compile; but does NOT lint

Bare in mind: Running my linter via NPM does pickup the error:
script in package.json:
`"lint:css": "stylelint ./**/*.{vue,scss} --fix",`
```
npm run lint:css

> piniata@0.0.0 lint:css
> stylelint ./**/*.{vue,scss} --fix


src/views/Home/test.scss
 5:9  ✖  Unexpected unknown property "clor"  property-no-unknown
 ```

_Originally posted by @timenengwerda in https://github.com/ModyQyW/vite-plugin-stylelint/issues/8#issuecomment-1131382030_

**Comment by ModyQyW** [comment]
I did some digging.

First, I add two rows in my plugin locally. So my plugin will print something I want to see.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/31850793/169253379-cdd9884c-4252-4b01-916e-07560412806e.png">

Then, I update the vue example `package.json` and install.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/31850793/169253126-f6310ab4-8993-44d9-9b74-b200d9ef32dc.png">

Also update `vite.plugin.ts`.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/31850793/169253567-c2ab1dd8-2e03-42b0-b52e-0a3a09198334.png">

Import `app.scss`.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/31850793/169253749-a11ef48d-dd82-4359-a710-8ccb3fc97ffd.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/31850793/169253844-871b13e4-f1a9-4b2f-a745-8f4ebac8cb2d.png">

Run dev. And I get nothing error. But I expected `app.scss` errors.

**Comment by ModyQyW** [comment]
No errors in page and console.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/169254383-0d7e8954-d507-482a-82af-0443ec61401d.png">

No errors in terminal. And I notice that no `app.scss` is logged.

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/31850793/169254261-ac77dfc6-4aec-4dd9-9b98-96b5a91db5bc.png">

Visit http://localhost:3001/__inspect/ and I found these.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/169254650-0a9ef29c-e4df-4916-a32f-4149f51d2d9e.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/169254722-4d894747-2730-46a9-8421-e684837ce383.png">

Vite DOES compiles `app.scss`, but in an unexpected way. The plugin expects to get `app.scss` in the `transform` hook so stylelint can work.

**Comment by ModyQyW** [comment]
No idea how to fix for now. Any PR or any idea will be appreciated. Thanks!

**Comment by timenengwerda** [comment]
Perhaps this actually *is* caused by this Vite issue: https://github.com/vitejs/vite/issues/8224

The comments state that downgrading your Vite version might help but that obviously doesn't(and perhaps can't) fix the issue in this plugin

**Comment by ModyQyW** [comment]
I am not sure. I think in this case, the file is compiled by `postcss` and `sass` so `app.scss` never comes to the `transform` hook.

**Comment by ModyQyW** [comment]
There is a new option called `lintOnStart` in v3.0.0, which may be helpful for such situations. Please have a try.

**Comment by timenengwerda** [comment]
> There is a new option called `lintOnStart` in v3.0.0, which may be helpful for such situations. Please have a try.

Thanks for the update! 
This gives you an error whenever you start the server(When you fix the error whilst its running the error doesn't clear so you'll have to restart); 

It doesn't give lint errors when the devServer is already running though.

**Comment by ModyQyW** [comment]
> It doesn't give lint errors when the devServer is already running though.

Yes. I can't find a neat way to hack into. PR welcome :)

**Comment by ModyQyW** [comment]
Six months have passed, and I've finally come up with an idea.

Since the `transform` hook can't handle files introduced by `@import`, why don't we jump out of the `transform` hook?

v3.3.0 introduces the `chokidar` option, which allows you to use `chokidar` as a listener so that `stylelint` can handle files introduced by `@import`! This is a new option, please try it out and give me feedback ❤

**Comment by ModyQyW** [comment]
I am closing this. Feel free to open another issue if you are facing problems using `chokidar` option. :)

**Comment by timenengwerda** [comment]
Thanks for sticking with this issue, it's much appreciated. I've had the chance to test this out. I didnt some searching and made some comments here that do not seem to belong to the stylelintConfig so I'm starting over with my findings:

Stylelinting scss files that are imported seem to work but it has some issues:
- Every mistake logs the entire lint errors. So if I have an indentation and a trailing semicolon error I see two error messages stating both the errors instead of being bundled into one error message (See screenshot)
- the `fix: true` doesn't work (anymore) in both Vue files and scss files. Having `cache `true/false doesn't seem to matter.

<img width="1196" alt="Screenshot 2022-12-02 at 09 55 07" src="https://user-images.githubusercontent.com/1368175/205254781-9d813fc8-4b6e-4d00-bc00-4c9fdcd50f6a.png">

**Comment by timenengwerda** [comment]
https://user-images.githubusercontent.com/1368175/205251306-d552744b-414e-433e-b04a-b4223521a7f9.mov

As the clip shows: On a save of the scss file it DOES actually refresh my page(see the status in my tab) but it doesn't re-apply the css. Refreshing the page manually doesn't do it either. Only saving the Vue file the scss is included in seems to work.

**Comment by timenengwerda** [comment]
Oh wait; hold on. I don't think this is an issue that's involved with Stylelint. The linter gives the proper messages etc on queue, it's just not compiling but that seems to be a different issue. I'll go check it out

**Comment by ModyQyW** [comment]
The second problem has been fixed and will be released in v3.3.2.

Digging he first problem...

**Comment by timenengwerda** [comment]
Works like a charm! This makes triggering errors a lot harder which makes it perfectly workable for me. Although I do think fixing the first problem is still a big win for everyone.

**Comment by ModyQyW** [comment]
Should be fine in v3.3.3. But I find another problem in <https://github.com/ModyQyW/vite-plugin-stylelint/issues/27>.
